language: cpp

compiler: clang

script:
  - cmake --build build --config Debug
  - ./build/test/acorntest

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-6.0
    packages:
      - cmake
      - llvm-6.0-dev
      - clang-6.0
      - libboost-regex-dev
