language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ./compiler/test/acorntest

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - cmake
      - llvm-4.0-dev
      - clang-4.0
      - libboost-regex-dev
