language: cpp

compiler: clang

script:
  - mkdir build
  - cd build
  - CXX=clang++-6.0 cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cd ..
  - CXX=clang++-6.0 cmake --build build --config Debug
  - ./build/test/acorntest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - cmake
      - clang-6.0
      - llvm-6.0-dev
      - libboost-regex-dev
