language: cpp

compiler: clang

script:
  - mkdir build
  - cd build
  - CC=clang-4.0 CXX=clang++-4.0 cmake ..
  - CC=clang-4.0 CXX=clang++-4.0 make
  - ./compiler/test/acorntest

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - cmake
      - llvm-4.0-dev
      - clang-4.0
      - libboost-regex-dev
